GoalApp/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :index, :create, :show]
end

GoalApp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

GoalApp/app/models/cheer.rb
class Cheer < ApplicationRecord

end

GoalApp/app/models/comment.rb
class Comment < ApplicationRecord
end

GoalApp/app/models/goal.rb
# == Schema Information
#
# Table name: goals
#
#  id         :bigint           not null, primary key
#  body       :text             not null
#  user_id    :integer          not null
#  private    :boolean          default(FALSE)
#  closed     :boolean          default(FALSE)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Goal < ApplicationRecord

  validates :body, :user_id, presence: true
  validates :private, inclusion: { in: [true, false]}
  validates :closed, inclusion: { in: [true, false]}

  has_many :cheers

  has_many :comments

  belongs_to :user
end

GoalApp/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  cheers_counter  :integer          default(12)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  validates :username, :password_digest, :session_token, :cheers_counter, presence: true
  validates :username, :session_token, uniqueness: true
  validates :password, length: {minimum: 6, allow_nil: true}

  attr_reader :password

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return nil unless user && user.password_digest.is_password?(password)
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64
  end

  after_initialize :ensure_session_token

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end


  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    bcrpypt_password = BCrypt::Password.new(self.password_digest)
    bcrpypt_password.is_password?(password)
  end

  has_many :goals

end

GoalApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?

  def current_user
    @current_user = User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def login!(user)
    session[:session_token] = user.reset_session_token!
  end

  def logout!
    current_user.reset_session_token!
    current_user = nil
    session[:session_token] = nil
  end
end

GoalApp/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    render :index
  end

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login!(@user)
      redirect_to users_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end

end

GoalApp/app/helpers/application_helper.rb
module ApplicationHelper
end

GoalApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoalApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if current_user %>
  <% else%>
  <a href="<%=new_user_url%>">Login</a>
  <% end%>
    <%= yield %>
  </body>
</html>

GoalApp/app/views/users/new.html.erb
<h2>Sign Up</h2>

<form action="<%= users_url %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label for="username">Username</label>
  <input id="username" type="text" name="user[username]">
  
  <label for="password">Password</label>
  <input id="password" type="text" name="user[password]">

  <input type="submit" value="Create User">

  


</form>